Repository utopia-os/utopia-map, pull requests merged in 2025-02, with the labels that each got.

#96 feat(source): setup unit tests
  .eslintignore
  .eslintrc.cjs
  package-lock.json
  package.json
  postcss.config.cjs
  setupTest.ts
  src/Components/Input/TextInput.spec.tsx
  src/Components/Input/__snapshots__/TextInput.spec.tsx.snap
  tsconfig.json
  vite.config.ts
Labels: feature

#97 feat(workflow): unit tests
  .github/workflows/test.unit.yml
Labels: feature

#117 feat(other): set up component testing
  cypress.config.ts
  cypress/support/commands.ts
  cypress/support/component-index.html
  cypress/support/component.ts
  package-lock.json
  package.json
  src/Components/Input/TextInput.cy.tsx
  tsconfig.json
Labels: feature

#125 refactor(docu): reference the docu URL in the README.md
  README.md
Labels: refactor

#124 feat(docu): group docs by category
  package.json
  src/Components/AppShell/AppShell.tsx
  src/Components/AppShell/Content.tsx
  src/Components/AppShell/SideBar.tsx
  src/Components/AppShell/Sitemap.tsx
  src/Components/Auth/LoginPage.tsx
  src/Components/Auth/RequestPasswordPage.tsx
  src/Components/Auth/SetNewPasswordPage.tsx
  src/Components/Auth/SignupPage.tsx
  src/Components/Auth/useAuth.tsx
  src/Components/Gaming/Modal.tsx
  src/Components/Gaming/Quests.tsx
  src/Components/Input/SelectBox.tsx
  src/Components/Input/TextAreaInput.tsx
  src/Components/Input/TextInput.tsx
  src/Components/Map/ItemForm.tsx
  src/Components/Map/ItemView.tsx
  src/Components/Map/Layer.tsx
  src/Components/Map/Permissions.tsx
  src/Components/Map/Subcomponents/ItemPopupComponents/PopupButton.tsx
  src/Components/Map/Subcomponents/ItemPopupComponents/PopupCheckboxInput.tsx
  src/Components/Map/Subcomponents/ItemPopupComponents/PopupStartEndInput.tsx
  src/Components/Map/Subcomponents/ItemPopupComponents/PopupTextAreaInput.tsx
  src/Components/Map/Subcomponents/ItemPopupComponents/PopupTextInput.tsx
  src/Components/Map/Subcomponents/ItemPopupComponents/StartEndView.tsx
  src/Components/Map/Subcomponents/ItemPopupComponents/TextView.tsx
  src/Components/Map/Tags.tsx
  src/Components/Map/UtopiaMap.tsx
  src/Components/Profile/ProfileForm.tsx
  src/Components/Profile/ProfileView.tsx
  src/Components/Profile/UserSettings.tsx
  src/Components/Templates/AttestationForm.tsx
  src/Components/Templates/CardPage.tsx
  src/Components/Templates/MapOverlayPage.tsx
  src/Components/Templates/MarketView.tsx
  src/Components/Templates/MoonCalendar.tsx
  src/Components/Templates/OverlayItemsIndexPage.tsx
  src/Components/Templates/SelectUser.tsx
  src/Components/Templates/TitleCard.tsx
Labels: feature

#123 feat(docu): include version in the title
  package.json
Labels: feature

#121 feat(docu): include internal types
  package-lock.json
  package.json
Labels: feature

#122 fix(source): type export via rollup plugin by using the correct input
  package.json
  rollup.config.js
  src/Components/AppShell/AppShell.tsx
  src/Components/AppShell/NavBar.tsx
  src/Components/AppShell/index.tsx
  src/Components/Auth/index.tsx
  src/Components/Auth/useAuth.tsx
  src/Components/Gaming/Quests.tsx
  src/Components/Map/Layer.tsx
  src/Components/Map/Permissions.tsx
  src/Components/Map/Subcomponents/Controls/GratitudeControl.tsx
  src/Components/Map/Subcomponents/ItemPopupComponents/TextView.tsx
  src/Components/Map/index.tsx
  src/Components/Profile/ProfileForm.tsx
  src/Components/Profile/UserSettings.tsx
  src/Components/Profile/index.tsx
  src/Components/Templates/OverlayItemsIndexPage.tsx
  src/index.tsx
  src/types/AssetsApi.d.ts
  src/types/Item.d.ts
  src/types/ItemType.d.ts
  src/types/ItemsApi.d.ts
  src/types/LayerProps.d.ts
  src/types/Permission.d.ts
  src/types/Tag.d.ts
  src/types/UserApi.d.ts
  src/types/UserItem.d.ts
  src/types/index.ts
  tsconfig.json
Labels: bug

#137 fix(docu): example2
  examples/2-static-layers/package-lock.json
  examples/2-static-layers/package.json
  examples/2-static-layers/src/App.tsx
  examples/2-static-layers/src/sample-data.ts
Labels: bug

#138 refactor(source): export point type
  .github/workflows/test.build.yml
  examples/1-basic-map/package-lock.json
  examples/1-basic-map/package.json
  examples/2-static-layers/package-lock.json
  examples/2-static-layers/package.json
  examples/2-static-layers/src/sample-data.ts
  src/Components/Map/Layer.tsx
Labels: refactor

#135 refactor(source): types for all auth related things
  src/Components/Auth/LoginPage.tsx
  src/Components/Auth/RequestPasswordPage.tsx
  src/Components/Auth/SetNewPasswordPage.tsx
  src/Components/Auth/SignupPage.tsx
  src/Components/Auth/useAuth.tsx
  src/Components/Profile/UserSettings.tsx
  src/types/UserApi.d.ts
  src/types/UserItem.d.ts
Labels: refactor

#133 refactor(source): define types and remove file-wide eslint disables
  src/Components/AppShell/SideBar.tsx
  src/Components/AppShell/SidebarSubmenu.tsx
  vite.config.ts
Labels: refactor

#150 fix(other): delayed build
  rollup.config.js
Labels: bug

#149 refactor(source): define more types
  src/Components/AppShell/Content.tsx
  src/Components/AppShell/ContextWrapper.tsx
  src/Components/Gaming/hooks/useQuests.tsx
  src/Components/Input/SelectBox.tsx
  src/Components/Input/TextAreaInput.tsx
  src/Components/Input/TextInput.tsx
  src/Components/Input/__snapshots__/TextInput.spec.tsx.snap
  src/Components/Map/hooks/useDebounce.tsx
  src/Components/Map/hooks/useLayers.tsx
  src/Components/Map/hooks/usePermissions.tsx
  vite.config.ts
Labels: refactor

#144 refactor(source): svg files & heroicons
  .eslintrc.cjs
  package-lock.json
  package.json
  rollup.config.js
  src/Components/AppShell/NavBar.tsx
  src/Components/Gaming/Quests.tsx
  src/Components/Map/Subcomponents/AddButton.tsx
  src/Components/Map/Subcomponents/Controls/FilterControl.tsx
  src/Components/Map/Subcomponents/Controls/GratitudeControl.tsx
  src/Components/Map/Subcomponents/Controls/LayerControl.tsx
  src/Components/Map/Subcomponents/Controls/LocateControl.tsx
  src/Components/Map/Subcomponents/Controls/QuestControl.tsx
  src/Components/Map/Subcomponents/Controls/SearchControl.tsx
  src/Components/Map/Subcomponents/Controls/SidebarControl.tsx
  src/Components/Map/Subcomponents/ItemPopupComponents/HeaderView.tsx
  src/Components/Map/Subcomponents/ItemPopupComponents/StartEndView.tsx
  src/Components/Profile/Subcomponents/ActionsButton.tsx
  src/Components/Profile/Subcomponents/AvatarWidget.tsx
  src/Components/Profile/Subcomponents/ContactInfoView.tsx
  src/Components/Profile/Subcomponents/LinkedItemsHeaderView.tsx
  src/Components/Profile/Subcomponents/MarkdownHint.tsx
  src/Components/Profile/Subcomponents/PlusButton.tsx
  src/Components/Profile/Subcomponents/SocialShareBar.tsx
  src/Components/Profile/Subcomponents/SocialShareButton.tsx
  src/assets/chevron.svg
  src/assets/fist.svg
  src/assets/layer.svg
  src/assets/markdown.svg
  src/assets/plus.svg
  src/assets/share/clipboard.svg
  src/assets/share/facebook.svg
  src/assets/share/linkedin.svg
  src/assets/share/telegram.svg
  src/assets/share/twitter.svg
  src/assets/share/whatsapp.svg
  src/assets/share/xing.svg
  src/assets/target.svg
  src/assets/targetDot.svg
  src/assets/user.svg
  src/types/SVG.d.ts
  tsconfig.json
  vite.config.ts
Labels: refactor

#154 refactor(other): rollup - fail when typescript has warnings or errors
  rollup.config.js
Labels: refactor

#118 refactor(workflow): refine change check filters
  .github/workflows/test.docs.yml
  .github/workflows/test.unit.yml
Labels: devops, refactor
